language: node_js
before_install:
  - curl -sf https://qualityctl.run/install/eslint | BINDIR=. sh
before_script:
  - qctl-eslint eslint --ext .js,.vue --ignore-path .gitignore .
cache:
  directories:
    - node_modules
  yarn: true
node_js:
  - 9
  - 8
